services:
  # MESIN MINISTACK (LOCALSTACK SIMULATOR)
  ministack:
    image: nahuelnucera/ministack
    container_name: pixiecloud-ministack
    ports:
      - "4566:4566" 
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=ap-southeast-3 
    volumes:
      - ./docker-init:/etc/localstack/init/ready.d:ro